#!/usr/bin/env swift

import Foundation

struct Manifest: Decodable {
    let assets: [Asset]
}

struct Asset: Decodable {
    let item: String
    let source: String
    let source_sha256: String
    let output: String
    let output_sha256: String
    let width: Int
    let height: Int
}

private func wrappedBase64(_ data: Data) -> String {
    let encoded = data.base64EncodedString()
    var lines: [String] = []
    var index = encoded.startIndex
    while index < encoded.endIndex {
        let end = encoded.index(index, offsetBy: 96, limitedBy: encoded.endIndex) ?? encoded.endIndex
        lines.append("            " + encoded[index..<end])
        index = end
    }
    return lines.joined(separator: "\n")
}

let repository = URL(fileURLWithPath: FileManager.default.currentDirectoryPath, isDirectory: true)
let assetsDirectory = repository.appending(path: "Assets/Elysium/HeldTools", directoryHint: .isDirectory)
let manifestURL = assetsDirectory.appending(path: "manifest.json")
let manifest = try JSONDecoder().decode(Manifest.self, from: Data(contentsOf: manifestURL))
let ordered = manifest.assets.sorted { $0.item < $1.item }

var source = """
// Generated by scripts/embed-held-tool-assets.swift from Blender-authored,
// manifest-bound assets. Do not hand-edit this file.

import Foundation

let blenderHeldToolVisualAssets: [String: HeldItemVisualAsset] = [
"""

for asset in ordered {
    let pngURL = assetsDirectory.appending(path: asset.output)
    let png = try Data(contentsOf: pngURL)
    source += """

    \(String(reflecting: asset.item)): HeldItemVisualAsset(
        itemName: \(String(reflecting: asset.item)),
        provider: "Faithful 64x normalized through Blender 5.1",
        modelTaskID: "blender-held-tools-v1",
        sourceSHA256: \(String(reflecting: asset.output_sha256)),
        width: \(asset.width), height: \(asset.height),
        sourceEntry: \(String(reflecting: asset.source)),
        sourceEntrySHA256: \(String(reflecting: asset.source_sha256)),
        pixelSource: .pngBase64(
"""
    source += "\n            \"\"\"\n"
    source += wrappedBase64(png) + "\n"
    source += "            \"\"\")),\n"
}
source += "\n]\n"

let destination = repository.appending(path: "Sources/Elysium/HeldToolGeneratedAssets.swift")
try source.write(to: destination, atomically: true, encoding: .utf8)
print("embedded \(ordered.count) Blender held-tool assets -> \(destination.path)")
